title: グラフィックレコーディング勉強会
email: info@graben.jp
description: >
  グラレコ勉強会のホームページです。
baseurl: ""
url: "http://grareco.jp" # the base hostname & protocol for your site
official_facebook_url: hoge
participant_facebook_url: hoge
page_offer_url: /offer.html
page_url_workshop: hoge

# Build settings
markdown: kramdown

# Exclude setting files
exclude:
- Gemfile
- Gemfile.lock
- package.json
- node_modules
